// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"os"

	authnjwt "github.com/kalandramo/bald/contrib/authn-jwt"
	"github.com/kalandramo/bald/cache"
	"github.com/kalandramo/bald-admin/internal/apiserver"
	"github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/auditlog"
	"github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/auth"
	"github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/dict"
	"github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/file"
	"github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/menu"
	identitybiz "github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/identity"
	mfabiz "github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/mfa"
	"github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/permission"
	"github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/secret"
	"github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/tenant"
	"github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/user"
	"github.com/kalandramo/bald-admin/internal/bootstrap"
)

// Injectors from wire.go:

// InitializeBiz 由 wire 生成实现：显式拼装 cache + 各 biz，依赖图编译期校验。
func InitializeBiz() (*apiserver.BizSet, error) {
	mainSigner := provideSigner()
	biz := auth.New(mainSigner)
	mainRedisAddr := provideRedisAddr()
	cache, err := newRedisCache(mainRedisAddr)
	if err != nil {
		return nil, err
	}
	secretBiz := secret.New(cache)
	tenantBiz := tenant.New()
	userBiz := user.New()
	menuBiz := menu.New()
	permissionBiz := permission.New()
	dictBiz := dict.New(cache)
	// T5：文件 biz——MinIO 桥接与 file.bucket 兜底桶名来自 bootstrap。构造期值
	// 拷贝必为 nil（InitBridges 在 BeforeStart 才赋值），main.go 在 InitBridges
	// 之后经 SetStorage 补注；未配置 storage.minio 段时保持 nil，biz 内判 nil
	// 返回明确错误。
	fileBiz := file.New(bootstrap.MinioStorage, bootstrap.FileBucket)
	// T6：审计查询 biz（只读，数据由写路径审计落库）。
	auditLogBiz := auditlog.New()
	// Wave 1.5：MFA biz——挑战存储（Redis）在 BeforeStart 经 SetChallenges 补注
	// （与 file.SetStorage / auth.SetCaptchaStore 同款时序约定：构造期配置未就绪）。
	mfaBiz := mfabiz.New(nil)
	// Wave 1.6：identity 扩展域（credential + login_policy，无外部依赖）。
	identityBiz := identitybiz.New()
	// T10：BizSet 收敛到 apiserver 包（bizset.go）；cache 留在装配局部
	// （仅 secret/dict 消费，server 层不知缓存实现）。
	bizSet := &apiserver.BizSet{
		Auth:       biz,
		Secret:     secretBiz,
		Tenant:     tenantBiz,
		User:       userBiz,
		Menu:       menuBiz,
		Permission: permissionBiz,
		Dict:       dictBiz,
		File:       fileBiz,
		AuditLog:   auditLogBiz,
		MFA:        mfaBiz,
		Identity:   identityBiz,
	}
	return bizSet, nil
}

// wire.go:

// redisAddr 是 wire 的命名类型别名，区分 string 依赖（避免多重绑定冲突）。
type redisAddr string

// provideRedisAddr 从 env 提供 Redis 地址（空=禁用缓存，直连 store）。
// T0 起完整 Redis 参数（addr/password/db）经 bootstrap.Configure 由配置段注入，
// 此处仅保留 secret 缓存的 env 兼容通道。
func provideRedisAddr() redisAddr { return redisAddr(os.Getenv("BALD_ADMIN_REDIS_ADDR")) }

// provideSigner 从 bootstrap 提供 RSA 私钥签发器（auth biz 依赖 Signer 接口）。
// 必须走 LazySigner：本函数在 main 构造期求值，彼时 InitBridges 尚未生成 Signer，
// 直接传包级变量会把 nil 快照固化进 Biz（login 签发即 panic）。
func provideSigner() authnjwt.Signer { return bootstrap.LazySigner() }

// newRedisCache 适配 redisAddr→bootstrap.BuildRedisCache（D1：cache/redis 适配器；
// 保留错误，Redis 不可达即启动失败）。addr 为空返回 nil（禁用态）。
func newRedisCache(addr redisAddr) (cache.Cache, error) {
	return bootstrap.BuildRedisCache(string(addr), "", 0)
}
