// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"os"

	authnjwt "github.com/kalandramo/bald/contrib/authn-jwt"
	"github.com/kalandramo/bald/cache"
	"github.com/kalandramo/bald-admin/internal/apiserver"
	"github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/auditlog"
	"github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/auth"
	dashbiz "github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/dashboard"
	"github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/dict"
	"github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/file"
	"github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/menu"
	msgbiz "github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/message"
	orgbiz "github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/org"
	taskbiz "github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/task"
	identitybiz "github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/identity"
	mfabiz "github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/mfa"
	"github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/permission"
	pgbiz "github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/permgroup"
	planbiz "github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/plan"
	langbiz "github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/language"
	portalbiz "github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/portal"
	cmbiz "github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/cachemonitor"
	"github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/secret"
	"github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/tenant"
	"github.com/kalandramo/bald-admin/internal/apiserver/biz/v1/user"
	"github.com/kalandramo/bald-admin/internal/bootstrap"
)

// Injectors from wire.go:

// InitializeBiz 由 wire 生成实现：显式拼装 cache + 各 biz，依赖图编译期校验。
//
// Wave 3：各 biz 的仓储改为**构造期注入**（此前 biz 在请求期读 bootstrap 包级
// 变量）。前提是 Wave 4.1 已把本函数的调用点移到 InitBridges **之后**——故此处
// 读 bootstrap.XxxStore 拿到的是已就绪的真实实例，不再有「构造期快照固化 nil」。
// （本文件为 wire 生成产物；wire 本项目未启用 wire.Build 生成链，故此处手工维护，
// 与 internal/apiserver/biz/v1/* 的 New 签名保持同步——见「待处理事项」。）
func InitializeBiz() (*apiserver.BizSet, error) {
	mainSigner := provideSigner()
	biz := auth.New(mainSigner, bootstrap.UserStore, bootstrap.TenantStore, bootstrap.ReloadPolicies)
	mainRedisAddr := provideRedisAddr()
	cache, err := newRedisCache(mainRedisAddr)
	if err != nil {
		return nil, err
	}
	secretBiz := secret.New(bootstrap.SecretStore, cache)
	tenantBiz := tenant.New(bootstrap.TenantStore)
	userBiz := user.New(bootstrap.UserStore)
	menuBiz := menu.New(bootstrap.MenuStore)
	permissionBiz := permission.New(bootstrap.PermissionStore, bootstrap.RolePolicyStore)
	dictBiz := dict.New(bootstrap.DictTypeStore, bootstrap.DictEntryStore, cache)
	// T5：文件 biz——元数据仓储 Wave 3 起构造期注入（InitBridges 已赋值）。
	// MinIO 桥接与 file.bucket 兜底桶名仍为运行期：storage.minio/s3 段经契约
	// provider 在 FromBootstrap 阶段 B 构造，构造期可能为 nil，main.go 在
	// InitBridges 之后经 SetStorage/SetObjectStorage 补注；未配置时保持 nil，
	// biz 内判 nil 返回明确错误。
	fileBiz := file.New(bootstrap.FileStore, bootstrap.MinioStorage, bootstrap.FileBucket)
	// T6：审计查询 biz（只读，数据由写路径审计落库）。
	auditLogBiz := auditlog.New(bootstrap.AuditStore)
	// Wave 1.5：MFA biz——因子仓储构造期注入；挑战存储（Redis）仍在 BeforeStart
	// 经 SetChallenges 补注（与 file.SetStorage / auth.SetCaptchaStore 同款时序约定）。
	mfaBiz := mfabiz.New(bootstrap.MFAFactorStore, nil)
	// Wave 1.6：identity 扩展域（credential + login_policy）。
	identityBiz := identitybiz.New(bootstrap.CredentialStore, bootstrap.LoginPolicyStore)
	// Wave 1.7：组织架构（org_unit 树 + position）。
	orgBiz := orgbiz.New(bootstrap.OrgUnitStore, bootstrap.PositionStore, bootstrap.UserStore)
	// Wave 2.3：任务调度（scheduler 在 BeforeStart 后经 SetScheduler 注入）。
	taskBiz := taskbiz.New(bootstrap.TaskStore)
	// Wave 2.5：站内消息（三表）。
	messageBiz := msgbiz.New(bootstrap.MessageStore, bootstrap.MessageCategoryStore,
		bootstrap.RecipientStore, bootstrap.UserStore)
	// Wave 3.4：首页分析（只读聚合）。
	dashboardBiz := dashbiz.New(bootstrap.AuditStore, bootstrap.RoleStore, bootstrap.UserStore)
	// Wave 4.1：权限组 + 策略评估日志。
	permGroupBiz := pgbiz.New(bootstrap.PermGroupStore, bootstrap.PolicyEvalLogStore)
	// Wave 4.2：套餐三件套。
	planBiz := planbiz.New(bootstrap.PlanStore, bootstrap.PlanModuleStore, bootstrap.PlanQuotaStore)
	languageBiz := langbiz.New(bootstrap.LanguageStore)
	portalBiz := portalbiz.New(bootstrap.UserStore, bootstrap.RoleStore,
		bootstrap.PermissionStore, bootstrap.MenuStore)
	cacheMonitorBiz := cmbiz.New(bootstrap.RedisClient)
	// T10：BizSet 收敛到 apiserver 包（bizset.go）；cache 留在装配局部
	// （仅 secret/dict 消费，server 层不知缓存实现）。
	bizSet := &apiserver.BizSet{
		Auth:       biz,
		Secret:     secretBiz,
		Tenant:     tenantBiz,
		User:       userBiz,
		Menu:       menuBiz,
		Permission: permissionBiz,
		Dict:       dictBiz,
		File:       fileBiz,
		AuditLog:   auditLogBiz,
		MFA:        mfaBiz,
		Identity:   identityBiz,
		Org:        orgBiz,
		Task:       taskBiz,
		Message:    messageBiz,
		Dashboard:  dashboardBiz,
		PermGroup:  permGroupBiz,
		Plan:       planBiz,
		Language:   languageBiz,
		Portal:     portalBiz,
		CacheMonitor: cacheMonitorBiz,
	}
	return bizSet, nil
}

// wire.go:

// redisAddr 是 wire 的命名类型别名，区分 string 依赖（避免多重绑定冲突）。
type redisAddr string

// provideRedisAddr 从 env 提供 Redis 地址（空=禁用缓存，直连 store）。
// T0 起完整 Redis 参数（addr/password/db）经 bootstrap.Configure 由配置段注入，
// 此处仅保留 secret 缓存的 env 兼容通道。
func provideRedisAddr() redisAddr { return redisAddr(os.Getenv("BALD_ADMIN_REDIS_ADDR")) }

// provideSigner 从 bootstrap 提供 RSA 私钥签发器（auth biz 依赖 Signer 接口）。
//
// Wave 4.2：InitializeBiz 已移到 InitBridges **之后**（Wave 4.1），故此处直接取
// 包级 Signer 即为已就绪的真实实例——原 LazySigner（请求期解析）已无必要，随之删除。
func provideSigner() authnjwt.Signer { return bootstrap.Signer }

// newRedisCache 适配 redisAddr→bootstrap.BuildRedisCache（D1：cache/redis 适配器；
// 保留错误，Redis 不可达即启动失败）。addr 为空返回 nil（禁用态）。
func newRedisCache(addr redisAddr) (cache.Cache, error) {
	return bootstrap.BuildRedisCache(string(addr), "", 0)
}
